### PR TITLE
Improved Design for Accessibility 

### PR DESCRIPTION
**Pull request by 00travelgirl00**
- Darker and larger fonts
- darker symbols
- underlined links 
bildschirmfoto 2017-11-20 um 23 03 05

### CODE REVIEW

**Comment by websupporter** [comment]
Hi @00travelgirl00,
thanks a lot for your pull request. These changes so far are only done in the style.min.css. I think they should be reflected in the [style.css](https://github.com/pluginkollektiv/antispam-bee/blob/master/css/styles.css) as well.

So, if other changes are done in the style.css and this file gets minified by the author, your changes wouldn't get lost.

**Comment by 2ndkauboy** [comment]
@websupporter: I can't see any minification script. Do you know which one was used? Or do we have any preference?

**Comment by websupporter** [comment]
@2ndkauboy so far we havent one I think. This would be quite nice actually. No preference on my site. I added one to [Cachify](https://github.com/pluginkollektiv/cachify/commit/d47a3caea4be098940aa43192ae0133b68e2ea0f), but all are cool. But we should leave this for another PR though.

**Comment by 00travelgirl00** [comment]
Bernhard forgot to change the code to load the style.css instead of style.min.css. I have just changed it. This script.min.js is still loading. Did we changed that as well?

**Comment by websupporter** [comment]
Hi @00travelgirl00,
sorry, that your PR got stale :(

I am currently comparing your PR to the default WP schema and I was wondering, if we could align this more with WP. What I mean, e.g. 

https://github.com/pluginkollektiv/antispam-bee/pull/161/files#diff-fe4aeb7ba4bfe5050b46d913b61e60aeR60

 wouldn't `#23282d` be a choice, which aligns more with the WP standards (and I guess by this still fullfill the AA standard.

For white backgrounds, I found `#32373c` in the admin area as a chosen colour.

I am not really an designer or accessibility expert, just from my guts I think `#000` is quite strong and maybe to follow the WP palette could be a way to go? Not that ASB did follow this way before :see_no_evil: :smile:

**Comment by websupporter** [comment]
I move this to "Future Release" for now.

**Comment by krafit** [comment]
@00travelgirl00 and I decided to close this PR for now and open a new a11y related pull request for the upcoming Antispam Bee version :)

**Pull request closed without merging**
