### PR TITLE
fix: populate reasons array before sending spam notice mail, refs #508

### PR DESCRIPTION
**Pull request by florianbrinkmann**

### CODE REVIEW

**Comment by pfefferle** [comment]
SonarCloud is throwing an error, we should either fix it or remove SonarCloud completely in favor of the local tests.

**Comment by florianbrinkmann** [comment]
As far as I see, the SonarCloud issue is about the SQL query in the `_is_db_spam` method, no idea why it pops up now (or I miss something in the SonarCloud report)

**Comment by stklcode** [comment]
This one is mostly a false positive imho.

Sonarqube points out a 15 step chain very well: a user can craft an HTTP request with malicious IP headers that are put into a generated SQL statement.

But this specific “user input“ will run through `_sanitize_ip()` which will not return any non-ip characters and thus won’t allow an SQL injection through IP headers.

If `filter_var` does not exist (is that the case with any PHP setup?), our fallback would allow values of invalid length and might open an attack vector for overflow/performance issues. But I guess this is more of a highly theoretical scenario.

**Review by Zodiac1978 — APPROVED** [review]
LGTM!

**Pull request merged**
