### PR TITLE
Adjust colors to fit 5.7. color palette

### PR DESCRIPTION
**Pull request by krafit**
see #378

### CODE REVIEW

**Comment by Zodiac1978** [comment]
Do you think this is a visible change? Or too subtle?
Do you have before/after screenshots?

**Comment by krafit** [comment]
@Zodiac1978  It's a slight change. You can see the difference if you see old and new side by side, but I don't think it's noticeable otherwise.

Bildschirmfoto 2021-07-08 um 10 32 53
before (left), after (right)

**Comment by Zodiac1978** [comment]
This looks fine and complete.

The only thing we could think about is "merging" some colors, like Grey20 and Grey30 and just go with Grey30 for example.

Or aim a higher goal and try to go even more with the new higher contrast colors. Statify seems to have this already:

Bildschirmfoto 2021-07-08 um 10 54 02

Bildschirmfoto 2021-07-08 um 10 54 23

**Comment by Zodiac1978** [comment]
UI changes are handled in https://github.com/pluginkollektiv/antispam-bee/issues/406

**Review by Zodiac1978 — APPROVED** [review]
LGTM

**Pull request merged**
