### PR TITLE
Remove Russian translation files

### LINKED ISSUE #15: Remove translation files when possible
We can safely remove any translation files from the plugin here that reached 100% on WordPress.org. 
So far only German is fully translated: https://translate.wordpress.org/projects/wp-plugins/antispam-bee/dev

This is a tracking ticket we can keep open a bit to slowly remove translation files and of course bring people to translate on WordPress.org.

### LINKED ISSUE #189: Remove russian language file
Russian language has its own language pack!
https://translate.wordpress.org/locale/ru/default/wp-plugins/antispam-bee

So we can remove the Russian language files from the plugin. 😃

### PR DESCRIPTION
**Pull request by krafit**
Things move fast, once @Zodiac1978 writes a tweet 🙃 
ru_RU is at 100% on .org now, so finally get to close #15 🎉 

closes #15
closes #189

### CODE REVIEW

**Comment by websupporter** [comment]
do we still need https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L474-L481 and the languages-folder?

**Comment by krafit** [comment]
I'm not sure about https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L474-L481, but I guess the languages-folder can go 🤔

**Comment by websupporter** [comment]
So lets remove the `lang` folder and reduce the text_domain load to `load_plugin_textdomain('antispam-bee' );`

From what I see, we still will need to load the textdomain of course :rofl:

**Comment by Zodiac1978** [comment]
> From what I see, we still will need to load the textdomain of course

Not necessarily. But if we want to drop it, we have to require WordPress 4.6:
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain

**Comment by websupporter** [comment]
Thanks @Zodiac1978, I would suggest for now to keep it then.

**Comment by websupporter** [comment]
hey @krafit, i just reduced the load_plugin_textdomain() a bit. If thats ok, I think, we can merge.

**Pull request merged**
