### PR TITLE
Adding checks for global prefixes and text domain values

### PR DESCRIPTION
**Pull request by 2ndkauboy**
See #33

### CODE REVIEW

**Comment by 2ndkauboy** [comment]
It seems that we are not running tests for `phpcs` right now, correct? At least this is only running `eslint` and `stylelint`: https://github.com/pluginkollektiv/antispam-bee/blob/master/.github/workflows/tests.yml#L99

**Review by pfefferle — APPROVED** [review]
LGTM!

**Comment by florianbrinkmann** [comment]
> It seems that we are not running tests for phpcs right now, correct? 

Yes, I think you are right

**Review by florianbrinkmann — APPROVED** [review]
LGTM

**Pull request merged**
