### PR TITLE
docs: fixed short description to meet 150 characters (#580)

### LINKED ISSUE #580: Reduce tags to 5 and limit short description to 150 characters
Readme: One or more tags were ignored. Please limit your plugin to 5 tags.
    Readme: The Short Description section is too long and was truncated. A maximum of 150 characters is supported.

Bildschirmfoto 2024-03-24 um 13 08 40

### PR DESCRIPTION
**Pull request by monkeyknifefighter**
Fixed short description to meet 150 characters.

Fix #580

### CODE REVIEW

**Comment by 2ndkauboy** [comment]
@monkeyknifefighter thanks for improving our English 😊

**Comment by Zodiac1978** [comment]
This only fixes 1/2 of #580 - we also need to reduce the tags to 5.

Not sure about the mentioning of "trackbacks" here. This is so dated, we possibly could just remove it. Thoughts?

**Comment by Zodiac1978** [comment]
Otherwise the PR is great! Thanks 👍

**Comment by 2ndkauboy** [comment]
Yes, I think trackback could be removed here.

@monkeyknifefighter would you like to try changing the description again?

**Review by 2ndkauboy — APPROVED** [review]

**Comment by Zodiac1978** [comment]
> Not sure about the mentioning of "trackbacks" here. This is so dated, we possibly could just remove it. Thoughts?

Anyone care to share a thought about this question?

**Pull request merged**
