### PR TITLE
Prepare 2.11.1 release

### PR DESCRIPTION
**Pull request by florianbrinkmann**

### CODE REVIEW

**Review by pfefferle — APPROVED** [review]

**Comment by Zodiac1978** [comment]
I have linked the PR with the issue (#458 ) and checked everything what is done. LGTM!

Why do you have removed the POT file? Looks like this still useful:
https://developer.wordpress.org/plugins/internationalization/localization/#pot-portable-object-template-files

Maybe this needs an update though?

**Comment by florianbrinkmann** [comment]
> Why do you have removed the POT file? Looks like this still useful.

I think I created that file during a test locally and forgot to remove it again before pushing the first commit, it is not part of the `master` branch.

**Comment by florianbrinkmann** [comment]
> I have linked the PR with the issue (https://github.com/pluginkollektiv/antispam-bee/issues/458 ) and checked everything what is done. LGTM!

thanks!

**Comment by Zodiac1978** [comment]
> Otherwise you don't need that file

For starting a new locale this would still be helpful, or not? Loco translate recommends using a generated POT file instead of extracting the strings yourself.
https://localise.biz/wordpress/plugin/manual/templates
This would help to get a new locale up and running without requiring 90% of translations.

> I think I created that file during a test locally and forgot to remove it again before pushing the first commit, it is not part of the master branch.

This explains why I did not found the `lang` folder in `master` branch 😂.

Then I'm fine with going on ...

**Pull request merged**
