### PR TITLE
Update links from Google+ and old website to GitHub wiki

### PR DESCRIPTION
**Pull request by 2ndkauboy**
I've created a `news` branch in the wiki with the archived Google+ pages. When the wiki branch is merged, this PR would link to the new news pages. I also updated some links that pointed to the old website to the matching wiki pages.

### CODE REVIEW

**Comment by websupporter** [comment]
Looks good to me, the failing test is because of #276. I didn't really follow up the discussions moving die documents from G+. I guess we merge, once the moval has taken place?

**Comment by Zodiac1978** [comment]
@2ndkauboy All those Github links do not work at the moment. Can you please create a PR for it or point me to the right place to do this on my own?

**Comment by 2ndkauboy** [comment]
The wiki has it's own Git repository and in it there is a `news` branch we would have to merge in order to get those links working.

On the hackathon someone was mentioning, that we might want to get rid of the wiki alltogether and only use the website. In that case, this PR would not make sense anymore.

Should I still merge the `news` branch as a temporary solution?

**Comment by Zodiac1978** [comment]
> On the hackathon someone was mentioning, that we might want to get rid of the wiki alltogether and only use the website. In that case, this PR would not make sense anymore.

@krafit Can you she dsome light on this question?

**Comment by krafit** [comment]
I incorporated @2ndkauboy Wonderfull work of saving the old Google+ posts into Antispam bees new website - https://antispambee.pluginkollektiv.org/news.
All according links were update in #327.

**Pull request closed without merging**
