### PR TITLE
bbPress Antispam integration

### PR DESCRIPTION
**Pull request by danielhuesken**
I have iproved the secret key generation so that it is not predictable and change every month automaticly.

I have spent it to new moethods for reuse on later bbPress Antispam integration.

Please test again bevore pull.

### CODE REVIEW

**Comment by danielhuesken** [comment]
Can be that it fixes #17 too.

**Comment by danielhuesken** [comment]
Now, the intrgration of bbPress Antisam is ready for test.

**Comment by swissspidy** [comment]
IIRC there was some discussion on Slack about this being more suitable for a separate plugin?

**Comment by krafit** [comment]
We've been carrying this PR around for some time now. I don't see bbPress Support in ASB until v3.0, so I'll close this PR for now. Would love to see this as an Add-on in the future!

**Pull request closed without merging**
