### PR TITLE
More default Regexes

### PR DESCRIPTION
**Pull request by websupporter**
Solves https://github.com/pluginkollektiv/antispam-bee/issues/18

### CODE REVIEW

**Comment by Zodiac1978** [comment]
I would like to see some documentation for this. (e.g. non-english words)

There is a way to provide non detected spam comments:
https://github.com/pluginkollektiv/antispam-bee/wiki/de-H%C3%A4ufige-Fragen#nicht-erkannten-spam-einreichen
https://docs.google.com/forms/d/e/1FAIpQLSeQlKVZZYsF1qkKz7U78B2wy_6s6I7aNSdQc-DGpjeqWx70-A/viewform?c=0&w=1

Here are the results:
https://docs.google.com/spreadsheets/d/1IJWa8nBlGasJhJbA3fvGnh-QPt4EhGTA9w5eZByGYs0/edit#gid=260223063

Would be great to add even more patterns.

**Comment by schlessera** [comment]
Matching substring `dress` as author seems to invite lots of false positives, as it can be part of legitimate names, like `Andressa`.

Also, why is `prada` included in Japanese, but not in English?

**Comment by Zodiac1978** [comment]
See #18 - this is just adopted from this child theme. If you want the answer to that question you have to ask the original developer ;)

I think we should remove "dress" then and include prada.

Furthermore we can add words like cialis, viagra, etc.

**Comment by websupporter** [comment]
Yes, it was just quickly done. Will add/remove as suggested later in the evening.

**Comment by sdellenb** [comment]
The RegExes are based on the spam I got a few years back. For some reason, I never got undetected spam that had "Prada". Maybe some other test kicked in first.

In the mean time, I've also added [viagra|cialis](https://github.com/sdellenb/twentyfifteen-rubenesque-child/blob/master/functions.php#L46), because such spam comments started to appear. 👍

**Comment by websupporter** [comment]
Thanks @sdellenb,
I have added those now to the body param too. Forgot about this possibility :smile:

**Comment by websupporter** [comment]
I did add the pattern found @Zodiac1978 blog: http://torstenlandsiedel.de/2017/01/08/custom-pattern-fuer-antispam-bee/

This marks comments not longer than two chars as spam.

**Comment by Zodiac1978** [comment]
We could check if the IP and Hostnames are valid:
http://stackoverflow.com/questions/106179/regular-expression-to-match-dns-hostname-or-ip-address

And we could check if there is an IP or email address instead of a regular Website given. Or is that too much?

**Comment by websupporter** [comment]
Basically the last commit removes the `2 char`-commit to enable Comments like "Ja", which are completly legit. Following the remarks here: https://github.com/Zodiac1978/custom-patterns-asb

**Pull request merged**
