### PR TITLE
show `upgrade_notice` also on plugin overview page

### PR DESCRIPTION
**Pull request by pfefferle**

### CODE REVIEW

**Comment by pfefferle** [comment]
fixes #498

**Comment by florianbrinkmann** [comment]
LGTM. PHPCS is complaining

**Comment by pfefferle** [comment]
Yes, I think it's the autop! Should I remove it?

**Comment by florianbrinkmann** [comment]
> Yes, I think it's the autop! Should I remove it?

Not sure, what do you mean @Zodiac1978 @2ndkauboy @krafit?

I think it would be great to be able to add links to the text, f.e. to a page with more details on pluginkollektiv.org, so maybe not strip all HTML but allow at least links.

**Comment by pfefferle** [comment]
Ok, will change it to use kses instead

**Review by florianbrinkmann — APPROVED** [review]
LGTM

**Pull request merged**
