### PR TITLE
Rollback country check #29

### LINKED ISSUE #29: Reaktivierung der Option "Bestimmte Länder blockieren/zulassen"
Guten Morgen ;)

Vielleicht könnt ihr euch an [den Tag](https://plus.google.com/+SergejMüller/posts/ZyquhoYjUyF) erinnern, wo ich zwei Plugin-Funktionen aus Kostengründen entfernen musste. Eine der beiden Funktionen war `Bestimmte Länder blockieren bzw. erlauben`.

Es hat sich auch rumgesprochen, dass ich https://ip2country.info gestartet habe: OpenSource-Projekte sollen es einfacher haben, IP-Adressen entsprechenden Ländern zuordnen zu können. Mit dem Dienst versuche ich mein Problem von damals zu lösen: Man habe ein OpenSource-Projekt und benötigt ein (kostenloses) GeoIP-Targeting.

Also: Theoretisch könnte man den Plugin-Filter  `Bestimmte Länder blockieren bzw. erlauben` wieder in Betrieb nehmen und mit ip2country.info verknüpfen. Man müsste nur den Code von damals wieder übernehmen (ist ja getaggt) und leicht anpassen (Request/Response). Mit anonymen IP-Adressen kann ip2country.info ebenfalls umgehen.

Was haltet ihr von der Idee und der Effektivität des Spam-Filters?

//cc @pixolin

### PR DESCRIPTION
**Pull request by sergejmueller**
Fixes #29

### CODE REVIEW

**Comment by Zodiac1978** [comment]
Version has to be changed to 2.7.0 and the conflict has to be resolved, but the PR/feature itself is fine and I would be very happy if we can bring this feature back to the plugin.

**Comment by websupporter** [comment]
I have checked this feature out and tested it a bit. I think too it is good to go. The only thing I was thinking about: 

https://github.com/pluginkollektiv/antispam-bee/pull/30/commits/035e26dbd2f0061e3a11accea4c637512beeba51#diff-33ae96de74050319957e1ac65615cf29R1697
Basically when you do activate this feature without giving a black or whitelist every comment will be spam.

**Comment by sergejmueller** [comment]
> Basically when you do activate this feature without giving a black or whitelist every comment will be spam.

`return false;` will marked the comment as no-spam, see [the function doc](https://github.com/pluginkollektiv/antispam-bee/pull/30/commits/035e26dbd2f0061e3a11accea4c637512beeba51#diff-33ae96de74050319957e1ac65615cf29R1674).

**Comment by schlessera** [comment]
Replaced by #61

**Pull request closed without merging**
