### PR TITLE
Replace ob_start() with `comment_form_field_comment` filter

### PR DESCRIPTION
**Pull request by florianbrinkmann**
Some users experience issues with ASB in combination with other plugins because we do not end the `ob_start()`, or, because the other plugins end it (#391 and #357). This PR removes the `ob_start()` and uses the `comment_form_field_comment` filter instead, as proposed by @pfefferle https://github.com/pluginkollektiv/antispam-bee/issues/357#issuecomment-729597129

### CODE REVIEW

**Comment by florianbrinkmann** [comment]
The filter should only run when the comment form is displayed, so I guess it is save to remove the checks from the function that were necessary before (?)

**Comment by Zodiac1978** [comment]
Thank you for the PR!

Just to be sure: This would make the option obsolete to look for comment forms on archive pages, or not? Because the filter would fire for each comment form. Then we could remove this option too - not sure if there other implications if we do this.

**Comment by florianbrinkmann** [comment]
Hm, yes, I guess you are right, that option should not be needed anymore then. I will give it a try locally and add the form to the archive page.

**Comment by florianbrinkmann** [comment]
Seems to work fine. The honeypot field is also displayed in the form on the comment form.

**Comment by florianbrinkmann** [comment]
We are using the value of the `always_allowed` option for two filters (https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L2733 and https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L2766). When we remove the option, we need to decide what to do with that parameter. Just removing it could lead to errors with users that use the filter with all three parameters.

**Comment by pfefferle** [comment]
The question is: should antispam bee also work with contact forms or other forms in general or only with "comments". That is why I have not made a PR up to now.

**Comment by Zodiac1978** [comment]
> should antispam bee also work with contact forms or other forms in general

Wouldn't those contact forms need other implementations (other Regex) and hopefully have their own filter hooks?

**Comment by florianbrinkmann** [comment]
> After the change will "only" work for comment forms, that uses the comment_form_field_comment filter.

The only situation where this would not work would be when the comment form is built manually, wouldn’t it? The filter is fired in the `comment_form()` function which should be **the** function when one wants to display a comment form(?)

> […] and hopefully have their own filter hooks?

I would also think that. And if, some day, ASB can be extended, the plugin that adds support for other forms would need to handle that :)

**Comment by Zodiac1978** [comment]
> After the change will "only" work for comment forms, that uses the comment_form_field_comment filter.

Is there a way to circumvent this filter, so that this approach does not work in every case?

**Comment by pfefferle** [comment]
Don't get me wrong, I second the PR, I only wanted to point out that it does not work exactly like it works now.

But @florianbrinkmann is right, maybe we should remove the `name="comment"` so that it can be implemented by other forms that have a textarea. Or that we use the `<from>` as anchor instead of the `<textarea>`.

**Comment by pfefferle** [comment]
...maybe not a good idea to try to make the implementation generic, but to add a generic version that can be implemented by plugin providers instead.

**Review by pfefferle — APPROVED** [review]

**Comment by florianbrinkmann** [comment]
> Don't get me wrong, I second the PR, I only wanted to point out that it does not work exactly like it works now.

You are right, there could be cases where it works now but does not work after the change (manually crafted comment forms). Should we target that change for a major release, because it is a (theoretically) breaking change?

**Comment by pfefferle** [comment]
Good point! I would second the major release version!

**Comment by florianbrinkmann** [comment]
- [ ] Set option like `asb_use_output_buffer` to `0` in `register_activation_hook()` and use the buffer only when that option is not there or `1`.
- [ ] Add Checkbox to opt in for the output buffer usage.

**Comment by florianbrinkmann** [comment]
I added the option to use output buffering instead of the filter. When the plugin is activated, this option is set to `0`, so the filter is used.

When the option is not set (for installations that update to the new version), the output buffering will be used and the option is checked. **Important:** to make that work, I needed to modify the `get_key()` method, so that it does not return `null` for both cases: the option is not there or the option value is `0`. That should not have effect on other code, because, for example, `! self::get_option( 'delete_data_on_uninstall' )` will be true for `self::get_option( 'delete_data_on_uninstall' )` being `0` or `null`.

**Comment by florianbrinkmann** [comment]
- [ ] Replace anonymous function (because PHP 5.2…)

**Review by pfefferle — APPROVED** [review]
The filter seems to work and the setting is default on, if I had a previous version installed and it is not active on new installations. Works as expected!

**Review by pfefferle — APPROVED** [review]

**Pull request merged**
