### PR TITLE
add the .travis.yml

### PR DESCRIPTION
**Pull request by websupporter**
Adds a basic travis.yml

Since we support PHP from 5.2x on, I've PHP support from 5.2 upwards.

### CODE REVIEW

**Comment by websupporter** [comment]
Since our test environment needs at least 5.5, we unfortunatly can't test below this PHP version.

**Comment by websupporter** [comment]
It looks like, we do not support HHVM right now. Since we never claimed, I remove this test for now. (see the result in https://travis-ci.org/pluginkollektiv/antispam-bee/jobs/198738611)

Same goes with the PHP nightly version (https://travis-ci.org/pluginkollektiv/antispam-bee/jobs/198738612), we do use functions, which will be `depreceated` in version 7.2, I think this is good to know and should be kept in the tests.

**Comment by websupporter** [comment]
I also uncommented nightly for now (basically to see if we get a clean test now).

**Comment by schlessera** [comment]
Merged with 5.5 for now. We should work on lowering the test requirements (non-blocking).

**Pull request merged**
